apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpc-mcp-flux-role
rules:
  - apiGroups: ["flux-framework.org"]
    resources: ["miniclusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

