apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hpc-mcp

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole-flux.yaml
  - clusterrolebinding-flux.yaml
  - clusterrole-slurm-exec.yaml
  - clusterrolebinding-slurm-exec.yaml
  - service.yaml
  - deployment.yaml
