apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpc-mcp-rb
  namespace: hpc-mcp
subjects:
  - kind: ServiceAccount
    name: hpc-mcp-sa
    namespace: hpc-mcp
roleRef:
  kind: Role
  name: hpc-mcp-role
  apiGroup: rbac.authorization.k8s.io
